import type React from "react"
import localFont from "next/font/local"

import { ReactQueryClientProvider } from "@/providers"

import "./globals.css"

// Fonts
const coiny = localFont({
  src: "./fonts/Coiny-Regular.ttf",
  variable: "--font-coiny",
  weight: "400",
  style: "normal",
  display: "swap",
})

const iconButtonStyle = {
  width: "44px",
  height: "44px",
  borderRadius: "50%",
  backgroundColor: "#f1f5f9",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  cursor: "pointer",
  transition: "all 0.3s ease",
  border: "none",
  padding: 0,
}


const inter = localFont({
  src: [
    { path: "./fonts/InterVariable.woff2", weight: "100 900", style: "normal" },
    { path: "./fonts/Inter-Bold.woff2", weight: "700", style: "normal" },
    { path: "./fonts/Inter-SemiBold.woff2", weight: "600", style: "normal" },
    { path: "./fonts/InterDisplay-Medium.woff2", weight: "500", style: "normal" },
  ],
  variable: "--font-inter",
  display: "swap",
})

// Metadata
export const metadata = {
  title: "Party Place and Rentals",
  description: "Generated by Party Place and Rentals",
  keywords: "Party Place and Rentals, Payment, Dashboard, Admin",
  authors: [{ name: "Techzilla" }],
  openGraph: {
    title: "Party Place and Rentals",
    description: "Shop the moments that keep You & Your kids smiling...",
    images: ["/hero.png"],
  },
  twitter: {
    card: "summary_large_image",
    title: "Party Place and Rentals",
    description: "Shop the moments that keep You & Your kids smiling...",
    images: ["/hero.png"],
  },
  icons: {
    icon: "/favicon-v2.ico?v=3",
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${coiny.variable} ${inter.variable} antialiased relative`} style={{ overflow: "hidden" }}>
        <ReactQueryClientProvider>
          {children}
          {/* COMING SOON OVERLAY */}
          <div
            style={{
              position: "fixed",
              inset: 0,
              zIndex: 9999,
             backgroundColor: "rgba(255, 255, 255, 0.95)", // black with 60% opacity
              color: "#1e293b",
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              justifyContent: "center",
              textAlign: "center",
              pointerEvents: "all",
              fontFamily: "var(--font-inter)",
              padding: "2rem",
              overflow: "hidden",
            }}
          >
            <style>
              {`
                @keyframes fadeInUp {
                  from { opacity: 0; transform: translateY(20px); }
                  to { opacity: 1; transform: translateY(0); }
                }
                @keyframes float {
                  0%, 100% { transform: translateY(0px); }
                  50% { transform: translateY(-8px); }
                }
              `}
            </style>

            {/* Header with Doughnut branding */}
            <div
              style={{
                position: "absolute",
                top: "60px",
                left: "50%",
                transform: "translateX(-50%)",
                display: "flex",
                alignItems: "center",
                gap: "8px",
              }}
            >
              <div
                style={{
                  width: "28px",
                  height: "28px",
               
                  borderRadius: "50%",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  color: "white",
                  fontSize: "14px",
                  fontWeight: "600",
                }}
              >
            <img
  src="https://cdn.builder.io/api/v1/image/assets/1662cc7878a14807a495bf21efd1ec7c/2edaecb760d5ecfabe8b85b71f478b16584a22ac?placeholderIfAbsent=true"
  alt="Company Logo"
  style={{ display: "block", margin: "0 auto", height: "56px", width: "74px", objectFit: "contain" }}
/>

              </div>
              <span
                style={{
                  fontSize: "16px",
                  fontWeight: "500",
                  color: "#1e293b",
                }}
              >
                Party Place and Rentals
              </span>
            </div>

            {/* Decorative leaf - left side */}
            <img
  src="https://pngimg.com/uploads/balloon/balloon_PNG4958.png"
  alt="Balloon"
  style={{
    position: "absolute",
    bottom: "35%",
    left: "8%",
    height: "60px",
    animation: "float 3s ease-in-out infinite",
    transform: "rotate(-15deg)",
  }}
/>


            {/* Decorative shapes - right side */}
            <div
              style={{
                position: "absolute",
                bottom: "25%",
                right: "5%",
                display: "flex",
                flexDirection: "column",
                gap: "10px",
              }}
            >
              <div
                style={{
                  width: "60px",
                  height: "60px",
                  backgroundColor: "#fbbf24",
                  borderRadius: "50%",
                  animation: "float 2.5s ease-in-out infinite",
                }}
              />
              <div
                style={{
                  width: "40px",
                  height: "40px",
                  backgroundColor: "#f97316",
                  borderRadius: "50%",
                  marginLeft: "20px",
                  animation: "float 2s ease-in-out infinite reverse",
                }}
              />
            </div>

            {/* Top decorative dots */}
            <div
              style={{
                position: "absolute",
                top: "25%",
                right: "12%",
                display: "flex",
                gap: "8px",
              }}
            >
              <div style={{ width: "8px", height: "8px", backgroundColor: "#fbbf24", borderRadius: "50%" }} />
              <div style={{ width: "8px", height: "8px", backgroundColor: "#f97316", borderRadius: "50%" }} />
              <div style={{ width: "8px", height: "8px", backgroundColor: "#ef4444", borderRadius: "50%" }} />
            </div>

            {/* Main Content Container */}
            <div
              style={{
                maxWidth: "350px",
                width: "100%",
                animation: "fadeInUp 1s ease-out forwards",
                marginTop: "40px",
              }}
            >
              {/* Cooking Pot Icon */}
              <div
                style={{
                  fontSize: "80px",
                  marginBottom: "40px",
                  animation: "float 2s ease-in-out infinite",
                  filter: "drop-shadow(0 4px 8px rgba(0,0,0,0.1))",
                }}
              >
              <img
  src="https://cdn.builder.io/api/v1/image/assets/1662cc7878a14807a495bf21efd1ec7c/2edaecb760d5ecfabe8b85b71f478b16584a22ac?placeholderIfAbsent=true"
  alt="Company Logo"
  style={{ display: "block", margin: "0 auto", height: "56px", width: "74px", objectFit: "contain" }}
/>

              </div>

              {/* "WE'RE STILL" Text */}
              <p
                style={{
                  fontSize: "12px",
                  color: "#64748b",
                  fontWeight: "500",
                  letterSpacing: "0.15em",
                  textTransform: "uppercase",
                  marginBottom: "8px",
                  fontFamily: "var(--font-inter)",
                }}
              >
                WE ARE STILL
              </p>

              {/* Main Heading */}
              <h1
                style={{
                  fontSize: "36px",
                  fontWeight: "700",
                  color: "#2563eb",
                  lineHeight: "1.1",
                  marginBottom: "24px",
                  fontFamily: "var(--font-inter)",
                }}
              >
                Cooking Our New Website.
              </h1>

              {/* Subtitle */}
              <p
                style={{
                  fontSize: "16px",
                  color: "#64748b",
                  lineHeight: "1.5",
                  marginBottom: "40px",
                  fontFamily: "var(--font-inter)",
                  fontWeight: "400",
                }}
              >
                We are going to launch our new website Very Soon.
                <br />
                Stay Tune.
              </p>

              {/* Notify Me Button */}
              <button
                style={{
                  backgroundColor: "#1e293b",
                  color: "white",
                  padding: "16px 32px",
                  borderRadius: "50px",
                  border: "none",
                  fontSize: "16px",
                  fontWeight: "500",
                  cursor: "pointer",
                  display: "flex",
                  alignItems: "center",
                  gap: "12px",
                  margin: "0 auto 60px auto",
                  transition: "all 0.3s ease",
                  boxShadow: "0 8px 25px rgba(30, 41, 59, 0.3)",
                  fontFamily: "var(--font-inter)",
                }}
              >
                <div
                  style={{
                    width: "24px",
                    height: "24px",
                    backgroundColor: "white",
                    borderRadius: "50%",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    fontSize: "12px",
                  }}
                >
                  📧
                </div>
                Notify Me
                <span style={{ fontSize: "18px", marginLeft: "4px" }}>›</span>
              </button>

           {/* Social Media Icons */}
<div
  style={{
    display: "flex",
    justifyContent: "center",
    gap: "20px",
  }}
>
  {/* Email Icon */}
  <a href="mailto:support@partyplaceandrentals.com" style={iconButtonStyle} title="Email Us">
    <img
      src="https://tse1.mm.bing.net/th/id/OIP.IpB5yPUkCFHOzlmM-O7ncAHaFW?rs=1&pid=ImgDetMain&o=7&rm=3"
      alt="Email"
      style={{ width: "24px", height: "24px", objectFit: "contain" }}
    />
  </a>

  {/* Facebook Icon */}
  <a href="https://www.facebook.com/partyplaceandrentals" target="_blank" rel="noopener noreferrer" style={iconButtonStyle} title="Facebook">
    <img
      src="https://upload.wikimedia.org/wikipedia/commons/0/05/Facebook_Logo_%282019%29.png"
      alt="Facebook"
      style={{ width: "24px", height: "24px", objectFit: "contain" }}
    />
  </a>

  {/* Instagram Icon */}
  <a href="https://www.instagram.com/partyplaceandrentals/" target="_blank" rel="noopener noreferrer" style={iconButtonStyle} title="Instagram">
    <img
      src="https://upload.wikimedia.org/wikipedia/commons/e/e7/Instagram_logo_2016.svg"
      alt="Instagram"
      style={{ width: "24px", height: "24px", objectFit: "contain" }}
    />
  </a>
</div>

            </div>
          </div>
        </ReactQueryClientProvider>
      </body>
    </html>
  )
}
