import localFont from "next/font/local";
import { ReactQueryClientProvider } from "@/providers";
import Script from "next/script"; // 👈 import Script
import "./globals.css";
import ClientLayout from "./ClientLayout";

// Fonts
const coiny = localFont({
  src: "./fonts/Coiny-Regular.ttf",
  variable: "--font-coiny",
  weight: "400",
  style: "normal",
  display: "swap",
});

const inter = localFont({
  src: [
    { path: "./fonts/InterVariable.woff2", weight: "100 900", style: "normal" },
    { path: "./fonts/Inter-Bold.woff2", weight: "700", style: "normal" },
    { path: "./fonts/Inter-SemiBold.woff2", weight: "600", style: "normal" },
    { path: "./fonts/Inter-ExtraBold.woff2", weight: "800", style: "normal" },
    { path: "./fonts/InterDisplay-Medium.woff2", weight: "500", style: "normal" },
  ],
  variable: "--font-inter",
  display: "swap",
});

// ✅ Metadata
export const metadata = {
  title: "Party Place and Rentals",
  description: "Generated by Party Place and Rentals",
  keywords: "Party Place and Rentals, Payment, Dashboard, Admin",
  authors: [{ name: "Techzilla" }],
  openGraph: {
    title: "Party Place and Rentals",
    description: "Shop the moments that keep You & Your kids smiling...",
    images: ["/hero.png"],
  },
  twitter: {
    card: "summary_large_image",
    title: "Party Place and Rentals",
    description: "Shop the moments that keep You & Your kids smiling...",
    images: ["/hero.png"],
  },
  icons: {
    icon: "/favicon-v3.ico?v=5",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* ✅ Force favicon-v3.ico everywhere */}
        <link rel="icon" href="/favicon-v3.ico?v=5" type="image/x-icon" />
        <link rel="shortcut icon" href="/favicon-v3.ico?v=5" type="image/x-icon" />
        <link rel="apple-touch-icon" href="/favicon-v3.ico?v=5" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-v3.ico?v=5" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-v3.ico?v=5" />
        <link rel="manifest" href="/favicon-v3.ico?v=5" />

        {/* Google Ads Tag */}
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=AW-17512936136"
        />
        <Script id="google-ads-tag" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'AW-17512936136');
          `}
        </Script>
      </head>
      <body className={`${coiny.variable} ${inter.variable} antialiased`}>
        <ReactQueryClientProvider>
          <ClientLayout>{children}</ClientLayout>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
