"use client"; // Client component directive

import localFont from "next/font/local";
import { ReactQueryClientProvider } from "@/providers";

import "./globals.css";

// New: Coiny font
const coiny = localFont({
  src: "./fonts/Coiny-Regular.ttf",
  variable: "--font-coiny",
  weight: "400",
  style: "normal",
  display: "swap",
});


// New: Inter variable font
const inter = localFont({
  src: [
    { path: "./fonts/InterVariable.woff2", weight: "100 900", style: "normal" },
    { path: "./fonts/Inter-Bold.woff2", weight: "700", style: "normal" },
    { path: "./fonts/Inter-SemiBold.woff2", weight: "600", style: "normal" },
    { path: "./fonts/Inter-ExtraBold.woff2", weight: "800", style: "normal" },
    { path: "./fonts/InterDisplay-Medium.woff2", weight: "500", style: "normal" },
  ],
  variable: "--font-inter",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <ReactQueryClientProvider>
        {/* Use Metadata API in Next.js 13+ */}
        <head>
          <title>Party Place and Rentals</title>
          <meta name="description" content="Generated by Party Place and Rentals" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <meta charSet="UTF-8" />
          <meta name="author" content="Techzilla" />
          <meta name="keywords" content="YCT, Payment, Dashboard, Admin" />
          
          {/* Add the favicon link */}
          <link rel="icon" href="/Vector.png" type="image/png" />
        </head>
        <body
          className={`${coiny.variable} ${inter.variable} antialiased`}
        >
          {children}
        </body>
      </ReactQueryClientProvider>
    </html>
  );
}
